{{- if .Values.branding }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: launchpad-{{ .Values.apolo_app_id }}-branding
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
binaryData:
  {{- if .Values.branding.logo }}
  logo: {{ .Values.branding.logo }}
  {{- end }}
  {{- if .Values.branding.favicon }}
  favicon: {{ .Values.branding.favicon }}
  {{- end }}
{{- if or .Values.branding.logoMediaType .Values.branding.faviconMediaType }}
data:
  {{- if .Values.branding.logoMediaType }}
  logo.meta: {{ .Values.branding.logoMediaType | quote }}
  {{- end }}
  {{- if .Values.branding.faviconMediaType }}
  favicon.meta: {{ .Values.branding.faviconMediaType | quote }}
  {{- end }}
{{- end }}
{{- end }}
