apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "launchpad.name" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "launchpad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "launchpad.selectorLabels" . | nindent 8 }}
        {{- include "launchpad.apoloPodLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: "ghcr"
      containers:
        - name: launchpad
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          command:
            - "python"
            - "-m"
            - "launchpad"
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: {{ .Values.port }}
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.port | quote }}
            - name: DB_HOST
              value: {{ .Values.postgresql.fullnameOverride }}
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecretName }}
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "launchpad"
            - name: KEYCLOAK_URL
              value: {{ include "keycloak.domain" . }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.defaultRealm }}
            - name: APOLO_PASSED_CONFIG
              value: {{ .Values.APOLO_PASSED_CONFIG | quote }}
            - name: LAUNCHPAD_INITIAL_CONFIG
              value: {{ .Values.LAUNCHPAD_INITIAL_CONFIG | quote }}
            - name: SELF_DOMAIN
              value: {{ include "launchpad.apiDomain" . }}
            - name: BASE_DOMAIN
              value: {{ .Values.domain }}
            - name: AUTH_MIDDLEWARE_NAME
              value: platform-{{ include "launchpad.name" . }}-auth-middleware
            - name: LAUNCHPAD_APP_ID
              value: {{ .Values.apolo_app_id | quote }}
            - name: LAUNCHPAD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "launchpad.admin-secret" . }}
                  key: LAUNCHPAD_ADMIN_PASSWORD
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
